
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nabila Basharahil
 */
public class NewJFrame extends javax.swing.JFrame {
    int bebek, sport, matik, diskon, harga, totaldiskon;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rd_bebek = new javax.swing.JRadioButton();
        rd_sport = new javax.swing.JRadioButton();
        rd_metik = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmb_merek = new javax.swing.JComboBox<>();
        t_harga = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t_diskon = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmb_jenis = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nama Pembeli");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 20, 66, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(160, 20, 200, 20);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Harga Motor"));

        rd_bebek.setText("Bebek");
        rd_bebek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_bebekActionPerformed(evt);
            }
        });

        rd_sport.setText(" Sport");
        rd_sport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_sportActionPerformed(evt);
            }
        });

        rd_metik.setText("Metik");
        rd_metik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_metikActionPerformed(evt);
            }
        });

        jLabel2.setText("MEREK");

        jLabel3.setText("JENIS");

        jLabel4.setText("HARGA");

        cmb_merek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Honda", "Yamaha ", "Suzuki ", "Kawasaki" }));
        cmb_merek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_merekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_merek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(rd_sport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rd_bebek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rd_metik)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmb_merek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rd_bebek)
                    .addComponent(rd_sport)
                    .addComponent(rd_metik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(t_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 60, 410, 160);
        jPanel1.getAccessibleContext().setAccessibleName("Identitas");
        jPanel1.getAccessibleContext().setAccessibleDescription("Identitas");

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pembayaran"));

        jLabel5.setText("DISKON");

        jLabel6.setText("TOTAL BAYAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_diskon, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(total))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t_diskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(60, 290, 320, 120);

        jLabel7.setText("JENIS BAYAR");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 240, 64, 14);

        cmb_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TUNAI", "KREDIT" }));
        cmb_jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_jenisActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_jenis);
        cmb_jenis.setBounds(170, 240, 80, 20);

        jButton1.setText("KELUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(403, 330, 90, 23);

        jButton2.setText("HITUNG");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 240, 110, 23);

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 550, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rd_sportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_sportActionPerformed
           if(rd_sport.isSelected())
        {
            t_harga.setText(String.valueOf(sport));
        }
    }//GEN-LAST:event_rd_sportActionPerformed

    private void cmb_merekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_merekActionPerformed
         if(cmb_merek.getSelectedItem().equals("Honda"))
        {
            bebek=11000000;
            sport=11500000;
            matik=12000000;
        }
            else if(cmb_merek.getSelectedItem().equals("Yamaha"))
            {
                bebek=12000000;
                sport=12500000;
                matik=13000000;
            }
                else if(cmb_merek.getSelectedItem().equals("Suzuki"))
                {
                    bebek=13000000;
                    sport=13500000;
                    matik=14000000;
                }
                    else if(cmb_merek.getSelectedItem().equals("Kawasaki"))
                    {
                        bebek=14000000;
                        sport=14500000;
                        matik=15000000;
                    }
        
    }//GEN-LAST:event_cmb_merekActionPerformed

    private void rd_bebekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_bebekActionPerformed
        if(rd_bebek.isSelected())
        {
            t_harga.setText(String.valueOf(bebek));
        }


    }//GEN-LAST:event_rd_bebekActionPerformed

    private void rd_metikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_metikActionPerformed
            if(rd_metik.isSelected())
        {
            t_harga.setText(String.valueOf(matik));
        }
    }//GEN-LAST:event_rd_metikActionPerformed

    private void cmb_jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_jenisActionPerformed
       if(cmb_merek.getSelectedItem().equals("Honda"))
        {
            if(cmb_jenis.getSelectedItem().equals("TUNAI"));
            {
                diskon=20;
                t_diskon.setText(String.valueOf(diskon));
            }if(cmb_jenis.getSelectedItem().equals("KREDIT"));
                {
                    diskon=8;
                    t_diskon.setText(String.valueOf(diskon));
                }
        }
        else if(cmb_merek.getSelectedItem().equals("Yamaha"))
        {
            if(cmb_jenis.getSelectedItem().equals("TUNAI"));
            {
                diskon=20;
                t_diskon.setText(String.valueOf(diskon));
            }
            if(cmb_jenis.getSelectedItem().equals("KREDIT"));
                {
                    diskon=7;
                    t_diskon.setText(String.valueOf(diskon));
                }
        }
       else if(cmb_merek.getSelectedItem().equals("Suzuki"))
        {
            if(cmb_jenis.getSelectedItem().equals("TUNAI"));
            {
                diskon=20;
                t_diskon.setText(String.valueOf(diskon));
            }
               if(cmb_jenis.getSelectedItem().equals("KREDIT"));
                {
                    diskon=6;
                    t_diskon.setText(String.valueOf(diskon));
                }
        }
        //KAWASAKI
        else if(cmb_merek.getSelectedItem().equals("Yamaha"))
        {
            if(cmb_jenis.getSelectedItem().equals("TUNAI"));
            {
                diskon=20;
                t_diskon.setText(String.valueOf(diskon));
            }
                if(cmb_jenis.getSelectedItem().equals("KREDIT")){
                    diskon=5;
                    t_diskon.setText(String.valueOf(diskon));
                }
        }
    }//GEN-LAST:event_cmb_jenisActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 harga=Integer.parseInt(t_harga.getText());
        diskon=Integer.parseInt(t_diskon.getText());
        totaldiskon=(diskon*harga)/100;
        t_diskon.setVisible(false);
        t_diskon.setText(String.valueOf(totaldiskon));
        total.setText(String.valueOf(total));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int answare = JOptionPane.showConfirmDialog(null, "Thanks", "Selesai", JOptionPane.OK_OPTION);
        if (answare == JOptionPane.OK_OPTION)
                {
                    dispose();
                }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_jenis;
    private javax.swing.JComboBox<String> cmb_merek;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rd_bebek;
    private javax.swing.JRadioButton rd_metik;
    private javax.swing.JRadioButton rd_sport;
    private javax.swing.JTextField t_diskon;
    private javax.swing.JTextField t_harga;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
